<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>সংগ্রহ সহায়তা: পোস্টসমূহ</h1>

       <p>একটি পোস্ট শুরু হয় একটি ছবি, লিঙ্ক, বা ফাইল দিয়ে যা আপনি শেয়ার করতে চান। আপনি সাইটে কনটেন্ট সংগ্রহ করে বা সরাসরি আপনার কম্পিউটার থেকে একটি ফাইল আপলোড করে একটি পোস্ট যোগ করতে পারেন। যেকোনো পোস্ট পুনরায় পোস্ট করা যেতে পারে, এবং সমস্ত পোস্ট তাদের মূল উৎসে সংযুক্ত থাকে।</p>
</article>


