<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1Ayuda: Colecciones</h1>
	<p>Una colecci&oacute;n es el espacio donde organizas tus publicaciones por tema. Por ejemplo, puedes guardar recursos para crear una introducci&oacute;n a un tema. Las colecciones pueden ser secretas o p&uacute;blicas e incluso puedes agregar una colecci&oacute;n dentro de otra colecci&oacute;n.</p>

	<section>
		<h2>Colecci&oacute;n predeterminada</h2>
		<p>Todos los usuarios tienen una colecci&oacute;n predeterminada creada autom&aacute;ticamente. Esto es para que tengas un espacio al que puedas comenzar a agregar publicaciones de inmediato. Las colecciones predeterminadas son privadas en un inicio, pero puedes cambiar la configuraci&oacute;n de privacidad como gustes. Tambi&eacute;n puedes cambiar el t&iacute;tulo y la descripci&oacute;n.</p>
	</section>

	<section>
		<h2>Crear una colecci&oacute;n</h2>
		<p>Puedes crear una colecci&oacute;n al dar clic en el bot&oacute;n de “Nueva Colecci&oacute;n” que se encuentra al ver tu lista de colecciones sobre la marcha o al guardar una publicaci&oacute;n.</p>

		<h3>Bot&oacute;n “Nueva colecci&oacute;n”</h3>
		<p>Despu&eacute;s de hacer clic en el bot&oacute;n, se te presentar&aacute;n algunos campos para personalizar y describir tu colecci&oacute;n. El &uacute;nico campo requerido es el t&iacute;tulo, pero puedes agregar una descripci&oacute;n m&aacute;s extensa de forma opcional.</p>

		<h3>"sobre la marcha"</h3>
		<p>Una colecci&oacute;n puede crearse al momento de guardar algo en el sitio. Al navegar por el contenido del sitio, puedes encontrar un bot&oacute;n de “Guardar” en la p&aacute;gina. Despu&eacute;s de hacer clic en ese bot&oacute;n, se te presentar&aacute; una opci&oacute;n para agregar el elemento a una colecci&oacute;n existente o crear una nueva colecci&oacute;n con el t&iacute;tulo que ingreses.</p>
	</section>

	<section>
		<h2>Crear una colecci&oacute;n privada</h2>
		<p>Tambi&eacute;n puedes crear colecciones privadas o secretas. Al crear o editar una colecci&oacute;n, habr&aacute; un campo de “Privacidad" con una lista desplegable de opciones. Selecciona "Privado" y guarda los cambios. Cuando una colecci&oacute;n es privada, aparecer&aacute; un peque&ntilde;o <span class="icon-private">candado</span> junto a su t&iacute;tulo.</p>
		<p><strong>Nota:</strong> Cuando una colecci&oacute;n es privada, no aparecer&aacute; en los resultados de b&uacute;squeda o en la lista de las <a href="<?php echo Route::url('index.php?option=com_collections'); ?>"> colecciones del sitio</a> .</p>
	</section>

	<section>
		<h2>Eliminar una colecci&oacute;n</h2>
		<p>Para eliminar una colecci&oacute;n, inicia sesi&oacute;n en tu cuenta y encuentra la colecci&oacute;n que deseas borrar en tu lista de colecciones. Al pasar el cursor sobre la colecci&oacute;n aparecer&aacute; un bot&oacute;n para eliminar. Al hacer clic, se te pedir&aacute; confirmar la eliminaci&oacute;n.</p>
		<p><strong>Nota:</strong> Eliminar una colecci&oacute;n <em>no</em> eliminar&aacute; las publicaciones encontradas dentro de la colecci&oacute;n.</p>
	</section>
</article>

