<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Ayuda de colecciones: seguir/dejar de seguir</h1>

	<h2>Seguir</h2>
	<p>Cuando sigues a alguien, sus publicaciones aparecen en tu p&aacute;gina de inicio. Puedes seguir todas las colecciones de alguien o s&oacute;lo las que m&aacute;s te gusten. Para administrar a qui&eacute;n sigues, ve a tu perfil, busca Colecciones y haz clic en Siguiendo.</p>

	<h2>Dejar de seguir</h2>
	<p>Cuando dejas de seguir a alguien, sus colecciones ya no aparecer&aacute;n en tu p&aacute;gina de inicio. Puedes dejar de seguir todas las colecciones de alguien, o s&oacute;lo aquellas que no te interesen.</p>
</article>
