<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Ayuda: Colecciones y publicaciones</h1>

	<p>Una publicaci&oacute;n comienza con una imagen, enlace o archivo que quieras compartir. Puedes agregar una publicaci&oacute;n al recolectar contenido del sitio o cargar un archivo desde tu computadora. Cualquier publicaci&oacute;n se puede volver a publicar y todas las publicaciones enlazan a su fuente.</p>
</article>
