<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Preguntas frecuentes sobre las etiquetas</h1>

	<nav>
		<ol>
			<li>
				<a href="#whataretags">&iquest;Qu&eacute; son las etiquetas?</a>
			</li>
			<li>
				<a href="#createtags">&iquest;C&oacute;mo creo una nueva etiqueta?</a>
			</li>
			<li>
				<a href="#deletetags">&iquest;C&oacute;mo elimino una etiqueta?</a>
			</li>
			<li>
				<a href="#removetag">&iquest;C&oacute;mo elimino una etiqueta de mi recurso, grupo, perfil, etc.?</a>
			</li>
			<li>
				<a href="#taglimit">&iquest;Hay un l&iacute;mite al n&uacute;mero de etiquetas que puedo agregar a un elemento?</a>
			</li>
			<li>
				<a href="#whotagged">&iquest;Puedo saber qui&eacute;n ha etiquetado el contenido de otro miembro?</a>
			</li>
		</ol>
	</nav>

	<section id="whataretags">
		<h3>&iquest;Qu&eacute; son las etiquetas?</h3>
		<p>Las etiquetas son palabras clave o categor&iacute;as. Ayudan a encontrar contenido, eventos o miembros que tienen algo en com&uacute;n o intereses similares. Las etiquetas se pueden agregar a grupos, perfiles, recursos, p&aacute;ginas wiki y eventos.</p>
	</section>

	<section id="createtags">
		<h3>&iquest;C&oacute;mo creo una nueva etiqueta?</h3>
		<p>Puedes agregar o eliminar las etiquetas que desees al crear o editar contenido, tu perfil, grupos, etc. Si una etiqueta a&uacute;n no existe, simplemente escribi&eacute;ndola en el campo del formulario "Etiquetas" se crear&aacute; y estar&aacute; disponible para que todos la usen. </p>
	</section>

	<section id="deletetags">
		<h3>&iquest;C&oacute;mo elimino una etiqueta?</h3>
		<p>No se puede. S&oacute;lo los administradores del sitio pueden eliminar etiquetas, pero puedes quitar etiquetas de un elemento de contenido o de tu perfil.</p>
	</section>

	<section id="removetag">
		<h3>&iquest;C&oacute;mo puedo quitar una etiqueta de un recurso, grupo, perfil, etc?</h3>
		<p>Al editar tu perfil, contenido, grupos, etc., puedes quitar etiquetas simplemente elimin&aacute;ndolas de la lista presentada en el campo del formulario "Etiquetas".</p>
	</section>

	<section id="taglimit">
		<h3>&iquest;Hay un l&iacute;mite al n&uacute;mero de etiquetas que puedo agregar un elemento?</h3>
		<p>No. Puedes agregar tantas etiquetas como desees al contenido etiquetable.</p>
	</section>

	<section id="whotagged">
		<h3>&iquest;Puedo saber qui&eacute;n ha etiquetado el contenido de otro miembro?</h3>
		<p>No. Ver qui&eacute;n etiquet&oacute; un elemento y qu&eacute; etiquetas agregaron no est&aacute; disponible actualmente para los usuarios.</p>
	</section>
</article>
