<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Ayuda: Etiquetas</h1>
	<p>Las etiquetas son palabras claves o categor&iacute;as Las etiquetas te ayudan a encontrar contenido, eventos y miembros que tienen algo en com&uacute;n o intereses similares. Se pueden agregar etiquetas a grupos, perfiles, recursos, p&aacute;ginas wiki y eventos.</p>
	<ul>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=tags&page=faqs'); ?>">Preguntas frecuentes</a>
		</li>
	</ul>
</article>
