<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Pomoc - kolekcje: obserwowanie</h1>

	<h2>Obserwuj</h2>
	<p>Posty obserwowanych użytkowników pojawiają się na tablicy. Można obserwować wszystkie lub wybrane kolekcje danego użytkownika. Listę obserwowanych można edytować w profilu, w zakładce Kolekcje, w sekcji Obserwowani.</p>

	<h2>Przestań obserwować</h2>
	<p>Posty użytkowników wyłączonych z listy obserwowanych przestają pojawiać się na tablicy. Można przestać obserwować wszystkie lub wybrane kolekcje danego użytkownika.</p>
</article>
