<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Pomoc - kolekcje: Wpisy</h1>

	<p>Posty zawierają obraz, link lub plik, który użytkownik chce udostępnić. Posty mogą zawierać materiał znaleziony w serwisie lub dodany bezpośrednio z dysku. Każdy post może być przekazany dalej, a linki zawarte w postach zachowują lokalizację źródła.</p>
</article>
