<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Najczęściej zadawane pytania - tagi</h1>

	<nav>
		<ol>
			<li>
				<a href="#whataretags">Co to są tagi?</a>
			</li>
			<li>
				<a href="#createtags">Jak utworzyć nowy tag?</a>
			</li>
			<li>
				<a href="#deletetags">Jak usunąć tag?</a>
			</li>
			<li>
				<a href="#removetag">Jak usunąć tag z zasobu/grupy/profilu itd?</a>
			</li>
			<li>
				<a href="#taglimit">Czy liczba tagów, które można przypisać danemu obiektowi, jest ograniczona?</a>
			</li>
			<li>
				<a href="#whotagged">Czy można sprawdzić, kto otagował materiały innego użytkownika?</a>
			</li>
		</ol>
	</nav>

	<section id="whataretags">
		<h3>Co to są tagi?</h3>
		<p>Tagi funkcjonują jako słowa kluczowe lub nazwy kategorii. Pomagają w wyszukiwaniu materiałów, wydarzeń, i użytkowników których łączą np. podobne zainteresowania. Tagi można dodawać w opisach grup, profilu użytkownika, zasobów, stron wiki i wydarzeń.</p>
	</section>

	<section id="createtags">
		<h3>Jak utworzyć nowy tag?</h3>
		<p>Podczas tworzenia lub edycji materiałów zamieszczanych w serwisie, profilu użytkownika, grup, itd. można dodawać lub usuwać tagi. Jeżeli żądany tag nie istnieje, należy wpisać właściwy ciąg znaków w polu “Tagi” formularza - tag zostanie utworzony i stanie się dostępny do użytku ogólnego w obrębie serwisu.</p>
	</section>

	<section id="deletetags">
		<h3>Jak usunąć tag?</h3>
		<p>Usuwanie tagów przez użytkownika nie jest możliwe - taką możliwość mają tylko administratorzy. Użytkownik może tylko usunąć tagi z oznaczeń danego materiału lub profilu.</p>
	</section>

	<section id="removetag">
		<h3>Jak usunąć tag z zasobu/grupy/profilu/itd.?</h3>
		<p>Podczas edycji treści, profilu, grup itd. można usuwać tagi poprzez edycję listy znajdującej się w polu “Tagi” formularza.</p>
	</section>

	<section id="taglimit">
		<h3>Czy liczba tagów którymi można oznaczyć dany obiekt jest ograniczona?</h3>
		<p>Nie. Użytkownik powinien być w stanie dodać dowolną liczbę tagów do materiałów i profili podlegających oznaczeniu w ten sposób.</p>
	</section>

	<section id="whotagged">
		<h3>Czy można sprawdzić kto dodał tagi do materiałów innego użytkownika?</h3>
		<p>Nie. Informacja o tym, kto dodał tagi nie jest obecnie udostępniana użytkownikom.</p>
	</section>
</article>
