<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Pomoc dotycząca tagów</h1>
	<p>Tagi są jak słowa kluczowe lub etykiety kategorii. Tagi pomagają znaleźć treści, wydarzenia oraz członków, których łączą wspólne cechy lub podobne zainteresowania. Tagi można dodawać do grup, profilu użytkownika, zasobów, stron wiki oraz wydarzeń.</p>
	<ul>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=tags&page=faqs'); ?>">FAQs</a>
		</li>
	</ul>
</article>
