<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Допомога з тегами</h1>
	<p>Теги — це як ключові слова або позначки категорій. Вони допомагають знаходити контент, події та учасників, які мають щось спільне або подібні інтереси. Теги можна додавати до груп, вашого профілю, ресурсів, вікі-сторінок та подій.</p>
	<ul>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=tags&page=faqs'); ?>">Поширені запитання</a>
		</li>
	</ul>
</article>