<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Aide sur les Collections : Suivre/Ne plus suivre</h1>

	<h2>Suivre</h2>
	<p>Lorsque vous suivez quelqu'un, leurs publications apparaissent dans votre flux en direct. Vous pouvez suivre toutes les collections de quelqu'un ou seulement celles que vous préférez. Pour gérer les personnes que vous suivez, rendez-vous sur votre profil, trouvez Collections, et cliquez sur Suivi.</p>

	<h2>Ne plus suivre</h2>
	<p>Lorsque vous ne suivez plus quelqu'un, leurs collections n'apparaissent plus dans votre flux en direct. Vous pouvez cesser de suivre toutes les collections de quelqu'un, ou seulement celles qui ne vous intéressent pas vraiment.</p>
</article>