<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Aide sur les Collections : Publications</h1>

	<p>Une publication commence par une image, un lien ou un fichier que vous souhaitez partager. Vous pouvez ajouter une publication en collectant du contenu sur le site ou en téléversant un fichier directement depuis votre ordinateur. Toute publication peut être partagée à nouveau, et toutes les publications renvoient à leur source.</p>
</article>