<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>ট্যাগ সহায়তা</h1>
	<p>ট্যাগ হলো কীওয়ার্ড বা বিভাগ লেবেলের মতো। ট্যাগ আপনাকে এমন বিষয়বস্তু, ইভেন্ট এবং সদস্য খুঁজতে সাহায্য করে যাদের মধ্যে কিছু মিল রয়েছে বা যারা একই ধরনের। গ্রুপ, আপনার প্রোফাইল, রিসোর্স, উইকি পেজ এবং ইভেন্টে ট্যাগ যোগ করা যেতে পারে।</p>
	<ul>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=tags&page=faqs'); ?>">প্রশ্নোত্তর</a>
		</li>
	</ul>
</article>
