<article>
	<h1>FAQ sur les mots-clés</h1>
	<nav>
		<ol>
			<li>
				<a href="#whataretags">Qu'est-ce que les mots-clés?</a>
			</li>
			<li>
				<a href="#createtags">Comment puis-je créer un nouveau mot-clé?</a>
			</li>
			<li>
				<a href="#deletetags">Comment puis-je supprimer un mot-clé?</a>
			</li>
			<li>
				<a href="#removetag">Comment puis-je retirer un mot-clé d'une ressource/d'un groupe/de mon profil/etc.?</a>
			</li>
			<li>
				<a href="#taglimit">Y a-t-il une limite au nombre de mots-clés que je peux ajouter à un élément?</a>
			</li>
			<li>
				<a href="#whotagged">Puis-je savoir qui a attribué un mot-clé au contenu d'un autre membre?</a>
			</li>
		</ol>
	</nav>

	<section id="whataretags">
		<h3>Qu'est-ce que les mots-clés?</h3>
		<p>Les mots-clés sont comme des étiquettes de catégorie. Les mots-clés vous aident à trouver du contenu, des événements et des membres qui ont quelque chose en commun ou des intérêts similaires. Les mots-clés peuvent être ajoutés aux groupes, à votre profil, aux ressources, aux pages de wiki et aux événements.</p>
	</section>

	<section id="createtags">
		<h3>Comment puis-je créer un mot-clé?</h3>
		<p>Lors de la création ou de la modification de contenu, de votre profil, de groupes, etc., vous pouvez ajouter ou supprimer des mots-clés à votre guise. Si un mot-clé n'existe pas encore, il vous suffit de le taper dans un champ de formulaire "Mots-clés" pour le créer et le rendre disponible pour tout le monde.</p>
	</section>

	<section id="deletetags">
		<h3>Comment puis-je supprimer un mot-clé?</h3>
		<p>Vous ne le pouvez pas. Seuls les administrateurs du site peuvent supprimer des mots-clés. Vous pouvez seulement supprimer des mots-clés d'un contenu ou d'un profil.</p>
	</section>

	<section id="removetag">
		<h3>Comment puis-je retirer un mot-clé d'une ressource/d'un groupe/de mon profil/etc.?</h3>
		<p>Lors de la modification de contenu, de votre profil, de groupes, etc., vous pouvez retirer des mots-clés en les supprimant simplement de la liste présentée dans le champ de formulaire "Mots-clés".</p>
	</section>

	<section id="taglimit">
		<h3>Y a-t-il une limite au nombre de mots-clés que je peux ajouter à un élément?</h3>
		<p>Non. Vous devriez pouvoir ajouter autant de mots-clés que vous le souhaitez aux contenus et profils étiquetable.</p>
	</section>

	<section id="whotagged">
		<h3>Puis-je savoir qui a attribué des mots-clés au contenu d'un autre membre?</h3>
		<p>Non. Les informations sur la personne ayant attribué des mots-clés sur un élément et les mots-clés qu'elle a ajoutés ne sont actuellement pas disponibles pour les utilisateurs.</p>
	</section>
</article>