<article>
	<h1>FAQ sur les balises</h1>
	<nav>
		<ol>
			<li>
				<a href="#whataretags">Qu'est-ce que les balises?</a>
			</li>
			<li>
				<a href="#createtags">Comment puis-je créer une nouvelle balise?</a>
			</li>
			<li>
				<a href="#deletetags">Comment puis-je supprimer une balise?</a>
			</li>
			<li>
				<a href="#removetag">Comment puis-je retirer une balise d'une ressource/d'un groupe/de mon profil/etc.?</a>
			</li>
			<li>
				<a href="#taglimit">Y a-t-il une limite au nombre de balises que je peux ajouter à un élément?</a>
			</li>
			<li>
				<a href="#whotagged">Puis-je savoir qui a étiqueté le contenu d'un autre membre?</a>
			</li>
		</ol>
	</nav>

	<section id="whataretags">
		<h3>Qu'est-ce que les balises?</h3>
		<p>Les balises sont comme des mots-clés ou des étiquettes de catégorie. Les balises vous aident à trouver du contenu, des événements et des membres qui ont quelque chose en commun ou des intérêts similaires. Les balises peuvent être ajoutées aux groupes, à votre profil, aux ressources, aux pages de wiki et aux événements.</p>
	</section>

	<section id="createtags">
		<h3>Comment puis-je créer une nouvelle balise?</h3>
		<p>Lors de la création ou de la modification de contenu, de votre profil, de groupes, etc., vous pouvez ajouter ou supprimer des balises à votre guise. Si une balise n'existe pas déjà, il vous suffit de la taper dans un champ de formulaire "Balises" pour la créer et la rendre disponible pour tout le monde.</p>
	</section>

	<section id="deletetags">
		<h3>Comment puis-je supprimer une balise?</h3>
		<p>Vous ne le pouvez pas. Seuls les administrateurs du site peuvent supprimer des balises. Vous pouvez seulement supprimer des balises d'un contenu ou d'un profil.</p>
	</section>

	<section id="removetag">
		<h3>Comment puis-je retirer une balise d'une ressource/d'un groupe/de mon profil/etc.?</h3>
		<p>Lors de la modification de contenu, de votre profil, de groupes, etc., vous pouvez retirer des balises en les supprimant simplement de la liste présentée dans le champ de formulaire "Balises".</p>
	</section>

	<section id="taglimit">
		<h3>Y a-t-il une limite au nombre de balises que je peux ajouter à un élément?</h3>
		<p>Non. Vous devriez pouvoir ajouter autant de balises que vous le souhaitez aux contenus et profils pouvant être balisés.</p>
	</section>

	<section id="whotagged">
		<h3>Puis-je savoir qui a étiqueté le contenu d'un autre membre?</h3>
		<p>Non. Les informations sur la personne ayant étiqueté un élément et les balises qu'elle a ajoutées ne sont actuellement pas disponibles pour les utilisateurs.</p>
	</section>
</article>