<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Aide sur les balises</h1>
	<p>Les balises sont comme des mots-clés ou des étiquettes de catégorie. Les balises vous aident à trouver du contenu, des événements et des membres qui ont quelque chose en commun ou des intérêts similaires. Les balises peuvent être ajoutées aux groupes, à votre profil, aux ressources, aux pages de wiki et aux événements.</p>
	<ul>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=tags&page=faqs'); ?>">FAQs</a>
		</li>
	</ul>
</article>