<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>合集帮助：关注 / 取消关注</h1>

	<h2>关注</h2>
	<p>当你关注某位用户时，他们发布的内容将显示在你的动态信息流中。你可以关注某位用户的所有合集，也可以只关注你最感兴趣的部分。如需管理你关注的对象，请前往你的个人资料页面，找到“合集”，并点击“正在关注”。</p>

	<h2>取消关注</h2>
	<p>当你取消关注某位用户后，他们的合集将不再显示在你的动态信息流中。你可以取消关注该用户的所有合集，或仅取消关注你不太感兴趣的部分。</p>
</article>
