<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Довідка щодо колекцій: Публікації</h1>

	<p>Публікація починається із зображення, посилання або файлу, яким ви хочете поділитися. Ви можете додати публікацію, збираючи контент на сайті, або завантажити файл безпосередньо зі свого комп’ютера. Будь-яку публікацію можна перепостити, і всі пости містять посилання на оригінальне джерело.</p>
</article>
