<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>标签常见问题</h1>

	<nav>
		<ol>
			<li>
				<a href="#whataretags">什么是标签？</a>
			</li>
			<li>
				<a href="#createtags">如何创建新标签？</a>
			</li>
			<li>
				<a href="#deletetags">如何删除标签？</a>
			</li>
			<li>
				<a href="#removetag">如何从资源/小组/我的个人资料等中移除标签？</a>
			</li>
			<li>
				<a href="#taglimit">我给一个条目添加标签的数量有限制吗？</a>
			</li>
			<li>
				<a href="#whotagged">我能知道是谁为其他成员的内容添加了标签吗？</a>
			</li>
		</ol>
	</nav>

	<section id="whataretags">
		<h3>什么是标签？</h3>
		<p>标签类似于关键词或类别标识。标签可以帮助你找到具有共同点或相似兴趣的内容、活动和成员。你可以为小组、个人资料、资源、维基页面以及活动添加标签。</p>
	</section>

	<section id="createtags">
		<h3>如何创建新标签？</h3>
		<p>在创建或编辑内容、个人资料、小组等时，你可以按需添加或移除标签。如果某个标签尚不存在，只需在“标签”表单字段中输入该标签，即可创建它，并使其对所有人可用。</p>
	</section>

	<section id="deletetags">
		<h3>如何删除标签？</h3>
		<p>无法删除。标签只能由网站管理员删除。你只能从某条内容或个人资料中移除标签。</p>
	</section>

	<section id="removetag">
		<h3>如何从资源/小组/我的个人资料等中移除标签？</h3>
		<p>在编辑内容、个人资料、小组等时，你可以在“标签”表单字段所显示的列表中，直接删除相应标签，从而将其移除。</p>
	</section>

	<section id="taglimit">
		<h3>我给一个条目添加标签的数量有限制吗？</h3>
		<p>没有。你可以为可添加标签的内容/个人资料添加任意数量的标签。</p>
	</section>

	<section id="whotagged">
		<h3>我能知道是谁为其他成员的内容添加了标签吗？</h3>
		<p>不能。目前用户无法查看是谁为某个条目添加了标签，以及添加了哪些标签。</p>
	</section>
</article>
