<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>标签帮助</h1>
	<p>标签类似于关键词或类别标识。标签可以帮助你找到具有共同点或相似兴趣的内容、活动和成员。你可以为小组、个人资料、资源、维基页面以及活动添加标签。</p>
	<ul>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=tags&page=faqs'); ?>"> 常见问题</a>
		</li>
	</ul>
</article>
